# fmt: off
class ValidationError(Exception): ...

# Token exceptions
class TokenValidationError(ValidationError): ...

# HH HTTP exceptions
class HHError(ValidationError): ...

class InvalidResponseError(HHError): ...

class GetTokenError(HHError): ...

class InvalidRequestError(GetTokenError): ...
class AccountNotFound(InvalidRequestError): ...
class AccountIsLocked(InvalidRequestError): ...
class PasswordInvalidated(InvalidRequestError): ...
class LoginNotVerified(InvalidRequestError): ...
class BadRedirectUrl(InvalidRequestError): ...
class TokenIsEmpty(InvalidRequestError): ...
class TokenNotFound(InvalidRequestError): ...
class CodeNotFound(InvalidRequestError): ...

class InvalidClientError(GetTokenError): ...

class InvalidGrantError(GetTokenError): ...
class TokenAlreadyRefreshed(InvalidGrantError): ...
class TokenNotExpired(InvalidGrantError): ...
class TokenWasRevoked(InvalidGrantError): ...
class BadToken(InvalidGrantError): ...
class CodeAlreadyUsed(InvalidGrantError): ...
class CodeExpired(InvalidGrantError): ...
class CodeRevoked(InvalidGrantError): ...
class TokenDeactivated(InvalidGrantError): ...

class UnsoportedGrantTypeError(GetTokenError): ...

class ForbiddenError(GetTokenError): ...

class UnknownError(GetTokenError): ...

class OAuthError(HHError): ...
class NotValidToken(OAuthError): ...
class TokenExpired(OAuthError): ...
class TokenRevoked(OAuthError): ...
class ApplicationNotFound(OAuthError): ...

class ServiceUnavailableError(HHError): ...

class InternalServiceError(HHError): ...


# DB manager exceptions
class DBManagerError(Exception): ...
class CommitError(DBManagerError): ...
# fmt: on


TOKEN_ERRORS_CONST = {
    "invalid_request": InvalidRequestError,
    "invalid_client": InvalidClientError,
    "invalid_grant": InvalidGrantError,
    "unsupported_grant_type": UnsoportedGrantTypeError,
    "forbidden": ForbiddenError,
}

AUTH_ERRORS_CONST = {
    "bad_authorization": NotValidToken,
    "token_expired": TokenExpired,
    "token_revoked": TokenRevoked,
    "application_not_found": ApplicationNotFound,
}
