version: "3.9"
services:
  web:
    image: fsow/headhunter:latest
    restart: always
    command: gunicorn main:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:1.21.1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web