"""add telegram_id field

Revision ID: d45168140ea1
Revises: 755e98e02f48
Create Date: 2021-08-18 11:35:39.328691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d45168140ea1"
down_revision = "755e98e02f48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint("unique tg id", ["telegram_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("unique tg id", type_="unique")

    # ### end Alembic commands ###
