"""Add expire_at field

Revision ID: 400b9d286ecc
Revises: f621125018b5
Create Date: 2021-08-15 20:38:04.143925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "400b9d286ecc"
down_revision = "f621125018b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("expire_at", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("users", "expire_at")
    # ### end Alembic commands ###
