"""rename users table to user

Revision ID: 8629b7efac2e
Revises: d45168140ea1
Create Date: 2021-08-18 17:51:16.599211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8629b7efac2e"
down_revision = "d45168140ea1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("users", "user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("user", "users")
    # ### end Alembic commands ###
