"""add response table, relation with user table

Revision ID: 612a58e3dbc2
Revises: 8629b7efac2e
Create Date: 2021-08-18 18:13:27.368794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612a58e3dbc2'
down_revision = '8629b7efac2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    # ### end Alembic commands ###
